# .cargo/config.toml

# Use mold linker for faster linking on macOS (both Intel and Apple Silicon)
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Optional: Slightly optimize dev builds (reduces debug info slightly)
# [profile.dev]
# debug = 1 